### ISSUE TITLE
Unable to save S4 decoder with mode=nplr

### ISSUE THREAD

**Issue by gregogiudici** [HazyResearch/state-spaces#105]
Hi, I'm implementing a decoder for audio generation (DDSP-style) using standalone S4 (V3).
I'd like to save checkpoints during the training and eventually the final model.
When training the model with S4D configuration (`mode=diag`) everything works well.

Instead, training the model with standard S4 configuration (`mode=nplr`) I get the following error:
 `RuntimeError: Cannot save multiple tensors or storages that view the same data as different types`.

Using CUDA extension for Cauchy and/or pykeops doesn't make a different.

I'm searching for a solution. Thanks in advance.

I'm on Ubuntu 18.04.4 LTS and this is my environment:
> python = 3.9.16
> torch = 2.0.1
> torchaudio = 0.13.1
> pytorch-cuda = 11.6
> pytorch-lightning = 1.9.3
> lightning = 2.0.2
> hydra-core = 1.3.2

And this is the train.log I obtained:
![image](https://github.com/HazyResearch/state-spaces/assets/103179440/4048a674-6c71-4156-b945-e2938d3ddd42)

**Comment by albertfgu** [comment]
Can you be more specific about the way you're saving the checkpoints? Do you have a custom train loop, or are you running our training script? If the latter, can you provide more details about the config you're using

One thing that stands out is that your `torch` and `torchaudio` versions don't seem compatible. `torchaudio=0.13.1` should be used with PyTorch 1.13 instead of 2.0: https://pytorch.org/get-started/previous-versions/

**Comment by gregogiudici** [comment]
I'm not running your training script. I'm new at using pytorch lightning so I'm using this [template](https://github.com/ashleve/lightning-hydra-template/tree/main) to learn it (modifyed for my model and the generative task).

I use default lightning callback [ModelCallback](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html) to save the checkpoints during evaluation with the following config:
```yaml
 model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  save_last: True
  save_top_k: 1 
  mode: "min" 
  auto_insert_metric_name: False 
  save_on_train_epoch_end: False 
```
I've also tryed different environment configuration, like the following example:
> python = 3.9.16
> torch = 1.13.1
> torchaudio = 0.13.1
> pytorch-cuda = 11.6
> pytorch-lightning = 1.5.10
> lightning = 2.0.2
> hydra-core = 1.3.2

obtaining the same `RunTimeError` all the times
